export const MESS = "http://localhost:8080/mess"
export const USER = "http://localhost:8080/user"
export const DAILYMENU = "http://localhost:8080/dailymenu"
export const FIXEDMENU = "http://localhost:8080/fixedmenu"
export const GETSINGLEMESS = "http://localhost:8080/mess/getonemess"
